package modelos;
// Generated 04-Jun-2023 21:51:48 by Hibernate Tools 4.3.1



/**
 * Espectador generated by hbm2java
 */
public class Espectador  implements java.io.Serializable {


     private Integer codigo;
     private Utilizador utilizador;
     private String nome;
     private String bairro;
     private String cidade;
     private String telefone;

    public Espectador() {
    }

    public Espectador(Utilizador utilizador, String nome, String bairro, String cidade, String telefone) {
       this.utilizador = utilizador;
       this.nome = nome;
       this.bairro = bairro;
       this.cidade = cidade;
       this.telefone = telefone;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Utilizador getUtilizador() {
        return this.utilizador;
    }
    
    public void setUtilizador(Utilizador utilizador) {
        this.utilizador = utilizador;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }




}


