package modelos;
// Generated 04-Jun-2023 21:51:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer codigo;
     private Utilizador utilizador;
     private String nome;
     private Date horaInicio;
     private Date horaFim;
     private Date dataEvento;
     private Integer numeroBilhete;
     private String localEvento;
     private Double valorEvento;
     private String descricao;
     private Set bilhetes = new HashSet(0);

    public Evento() {
    }

	
    public Evento(String descricao) {
        this.descricao = descricao;
    }
    public Evento(Utilizador utilizador, String nome, Date horaInicio, Date horaFim, Date dataEvento, Integer numeroBilhete, String localEvento, Double valorEvento, String descricao, Set bilhetes) {
       this.utilizador = utilizador;
       this.nome = nome;
       this.horaInicio = horaInicio;
       this.horaFim = horaFim;
       this.dataEvento = dataEvento;
       this.numeroBilhete = numeroBilhete;
       this.localEvento = localEvento;
       this.valorEvento = valorEvento;
       this.descricao = descricao;
       this.bilhetes = bilhetes;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Utilizador getUtilizador() {
        return this.utilizador;
    }
    
    public void setUtilizador(Utilizador utilizador) {
        this.utilizador = utilizador;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFim() {
        return this.horaFim;
    }
    
    public void setHoraFim(Date horaFim) {
        this.horaFim = horaFim;
    }
    public Date getDataEvento() {
        return this.dataEvento;
    }
    
    public void setDataEvento(Date dataEvento) {
        this.dataEvento = dataEvento;
    }
    public Integer getNumeroBilhete() {
        return this.numeroBilhete;
    }
    
    public void setNumeroBilhete(Integer numeroBilhete) {
        this.numeroBilhete = numeroBilhete;
    }
    public String getLocalEvento() {
        return this.localEvento;
    }
    
    public void setLocalEvento(String localEvento) {
        this.localEvento = localEvento;
    }
    public Double getValorEvento() {
        return this.valorEvento;
    }
    
    public void setValorEvento(Double valorEvento) {
        this.valorEvento = valorEvento;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getBilhetes() {
        return this.bilhetes;
    }
    
    public void setBilhetes(Set bilhetes) {
        this.bilhetes = bilhetes;
    }




}


