package modelos;
// Generated 04-Jun-2023 21:51:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Utilizador generated by hbm2java
 */
public class Utilizador  implements java.io.Serializable {


     private Integer codigo;
     private String email;
     private String senha;
     private String perfil;
     private Set espectadors = new HashSet(0);
     private Set eventos = new HashSet(0);
     private Set bilhetes = new HashSet(0);

    public Utilizador() {
    }

    public Utilizador(String email, String senha, String perfil, Set espectadors, Set eventos, Set bilhetes) {
       this.email = email;
       this.senha = senha;
       this.perfil = perfil;
       this.espectadors = espectadors;
       this.eventos = eventos;
       this.bilhetes = bilhetes;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public Set getEspectadors() {
        return this.espectadors;
    }
    
    public void setEspectadors(Set espectadors) {
        this.espectadors = espectadors;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }
    public Set getBilhetes() {
        return this.bilhetes;
    }
    
    public void setBilhetes(Set bilhetes) {
        this.bilhetes = bilhetes;
    }




}


